services:
  teleoperation:
    image: robot-modules/teleoperation:humble

    build:
      context: .
      dockerfile: teleoperation/Dockerfile

    network_mode: host

    volumes:
      - /dev/input:/dev/input
      - ./:/teleoperation

    environment:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}

    command: ros2 launch joy_bringup joy_launch.py