joy_teleop_twist_ref:
  ros__parameters:
    max_vel: 0.20
    scales: 1.0
    wheel_base: 0.2

joy_service_pkg:
  ros__parameters:
    joy_service: true
    arm_button: 0
    reset_button: 6

joy:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 0.0
    sticky_buttons: False
    coalesce_interval_ms: 1

teleop_twist_joy:
  ros__parameters:
      require_enable_button: True
      enable_button: 10
      enable_turbo_button: -1
      axis_linear.x: 1
      axis_linear.y: 2
      axis_linear.z: 3
      scale_linear.x: 1.0
      scale_linear.y: 1.0
      scale_linear.z: 0.0
      axis_angular.yaw: 2
      scale_angular.yaw: 1.0
      publish_stamped_twist: False
